### ISSUE TITLE
No stories shown

### ISSUE THREAD

**Issue by someone857** [ifedapoolarewaju/igstories#3]
Stories are not loading anymore. 

First error:
(node:5775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

After further investigation, I narrowed down to searchUsers function on instagram.js file. For me, call for `Client.Feed.UserStory` is failing with the following message:
RequestError: Too many reels requested

**Comment by ifedapoolarewaju** [comment]
issue is now fixed
